"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenRoyaltiesHandler__factory = exports.TokenRoyalties__factory = exports.TokenFactory721__factory = exports.TokenFactory1155__factory = exports.TokenCollectibles721__factory = exports.Token1155__factory = exports.ITokenRoyalties__factory = exports.ITokenFactory721__factory = exports.ITokenFactory1155__factory = exports.IToken721__factory = exports.IToken1155__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IToken1155__factory_1 = require("./IToken1155__factory");
Object.defineProperty(exports, "IToken1155__factory", { enumerable: true, get: function () { return IToken1155__factory_1.IToken1155__factory; } });
var IToken721__factory_1 = require("./IToken721__factory");
Object.defineProperty(exports, "IToken721__factory", { enumerable: true, get: function () { return IToken721__factory_1.IToken721__factory; } });
var ITokenFactory1155__factory_1 = require("./ITokenFactory1155__factory");
Object.defineProperty(exports, "ITokenFactory1155__factory", { enumerable: true, get: function () { return ITokenFactory1155__factory_1.ITokenFactory1155__factory; } });
var ITokenFactory721__factory_1 = require("./ITokenFactory721__factory");
Object.defineProperty(exports, "ITokenFactory721__factory", { enumerable: true, get: function () { return ITokenFactory721__factory_1.ITokenFactory721__factory; } });
var ITokenRoyalties__factory_1 = require("./ITokenRoyalties__factory");
Object.defineProperty(exports, "ITokenRoyalties__factory", { enumerable: true, get: function () { return ITokenRoyalties__factory_1.ITokenRoyalties__factory; } });
var Token1155__factory_1 = require("./Token1155__factory");
Object.defineProperty(exports, "Token1155__factory", { enumerable: true, get: function () { return Token1155__factory_1.Token1155__factory; } });
var TokenCollectibles721__factory_1 = require("./TokenCollectibles721__factory");
Object.defineProperty(exports, "TokenCollectibles721__factory", { enumerable: true, get: function () { return TokenCollectibles721__factory_1.TokenCollectibles721__factory; } });
var TokenFactory1155__factory_1 = require("./TokenFactory1155__factory");
Object.defineProperty(exports, "TokenFactory1155__factory", { enumerable: true, get: function () { return TokenFactory1155__factory_1.TokenFactory1155__factory; } });
var TokenFactory721__factory_1 = require("./TokenFactory721__factory");
Object.defineProperty(exports, "TokenFactory721__factory", { enumerable: true, get: function () { return TokenFactory721__factory_1.TokenFactory721__factory; } });
var TokenRoyalties__factory_1 = require("./TokenRoyalties__factory");
Object.defineProperty(exports, "TokenRoyalties__factory", { enumerable: true, get: function () { return TokenRoyalties__factory_1.TokenRoyalties__factory; } });
var TokenRoyaltiesHandler__factory_1 = require("./TokenRoyaltiesHandler__factory");
Object.defineProperty(exports, "TokenRoyaltiesHandler__factory", { enumerable: true, get: function () { return TokenRoyaltiesHandler__factory_1.TokenRoyaltiesHandler__factory; } });
