"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IToken1155__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_to",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "_qty",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_price",
                type: "uint256",
            },
            {
                internalType: "string",
                name: "_tokenURI",
                type: "string",
            },
            {
                internalType: "contract IRoyaltiesConfig",
                name: "_royaltiesConfig",
                type: "address",
            },
        ],
        name: "mintToken",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "_to",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "_token",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "_qty",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "_pending",
                type: "bool",
            },
        ],
        name: "purchaseToken",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IToken1155__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IToken1155__factory = IToken1155__factory;
IToken1155__factory.abi = _abi;
