"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITokenFactory1155__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "contract IRoyalties",
                name: "_royalties",
                type: "address",
            },
        ],
        name: "createToken",
        outputs: [
            {
                internalType: "contract IToken1155",
                name: "collectible",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class ITokenFactory1155__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ITokenFactory1155__factory = ITokenFactory1155__factory;
ITokenFactory1155__factory.abi = _abi;
