"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITokenRoyalties__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "uint256",
                name: "tokenId",
                type: "uint256",
            },
        ],
        name: "getCostPerToken",
        outputs: [
            {
                internalType: "uint256",
                name: "",
                type: "uint256",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "ownerAddress",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "token",
                type: "uint256",
            },
            {
                internalType: "uint256",
                name: "total",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "reclaim",
                type: "bool",
            },
        ],
        name: "transferPendingToken",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class ITokenRoyalties__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.ITokenRoyalties__factory = ITokenRoyalties__factory;
ITokenRoyalties__factory.abi = _abi;
