/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IToken1155, IToken1155Interface } from "../../tokens/IToken1155";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_qty",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
      {
        internalType: "contract IRoyaltiesConfig",
        name: "_royaltiesConfig",
        type: "address",
      },
    ],
    name: "mintToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_token",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_qty",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_pending",
        type: "bool",
      },
    ],
    name: "purchaseToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IToken1155__factory {
  static readonly abi = _abi;
  static createInterface(): IToken1155Interface {
    return new utils.Interface(_abi) as IToken1155Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IToken1155 {
    return new Contract(address, _abi, signerOrProvider) as IToken1155;
  }
}
