/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITokenFactory1155,
  ITokenFactory1155Interface,
} from "../../tokens/ITokenFactory1155";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IRoyalties",
        name: "_royalties",
        type: "address",
      },
    ],
    name: "createToken",
    outputs: [
      {
        internalType: "contract IToken1155",
        name: "collectible",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITokenFactory1155__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenFactory1155Interface {
    return new utils.Interface(_abi) as ITokenFactory1155Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITokenFactory1155 {
    return new Contract(address, _abi, signerOrProvider) as ITokenFactory1155;
  }
}
