"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IToken721__factory = void 0;
const ethers_1 = require("ethers");
const _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "_to",
                type: "address",
            },
            {
                internalType: "string[]",
                name: "uris",
                type: "string[]",
            },
        ],
        name: "mintMultipleTokens",
        outputs: [
            {
                internalType: "uint256[]",
                name: "tokenIds",
                type: "uint256[]",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            {
                internalType: "address",
                name: "_to",
                type: "address",
            },
            {
                internalType: "uint256",
                name: "_token",
                type: "uint256",
            },
            {
                internalType: "bool",
                name: "_pendingPayment",
                type: "bool",
            },
        ],
        name: "purchaseToken",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
];
class IToken721__factory {
    static createInterface() {
        return new ethers_1.utils.Interface(_abi);
    }
    static connect(address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    }
}
exports.IToken721__factory = IToken721__factory;
IToken721__factory.abi = _abi;
