/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRoyalties__factory } from "./IRoyalties__factory";
export { Royalties__factory } from "./Royalties__factory";
