"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Royalties__factory = exports.IRoyalties__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IRoyalties__factory_1 = require("./IRoyalties__factory");
Object.defineProperty(exports, "IRoyalties__factory", { enumerable: true, get: function () { return IRoyalties__factory_1.IRoyalties__factory; } });
var Royalties__factory_1 = require("./Royalties__factory");
Object.defineProperty(exports, "Royalties__factory", { enumerable: true, get: function () { return Royalties__factory_1.Royalties__factory; } });
