/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRoyalties,
  IRoyaltiesInterface,
} from "../../royalties/IRoyalties";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "entity",
        type: "address",
      },
    ],
    name: "claimRoyalties",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "grantRoyaltiesTo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "entity",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalUSDC",
        type: "uint256",
      },
    ],
    name: "recordRoyalties",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRoyalties__factory {
  static readonly abi = _abi;
  static createInterface(): IRoyaltiesInterface {
    return new utils.Interface(_abi) as IRoyaltiesInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRoyalties {
    return new Contract(address, _abi, signerOrProvider) as IRoyalties;
  }
}
