/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as royalties from "./royalties";
export * as tests from "./tests";
export * as tokens from "./tokens";
